### ISSUE TITLE
Compilation errors with 0.4.0-rc

### ISSUE THREAD

**Issue by ushinnary** [thaw-ui/thaw#342]
Hello, i've found out that once i add thaw in a project (i used an actix starter from leptos), i get an errors on compile.
Code that gets an error :
```rs
#[server(AuthCheck, "/api")]
pub async fn auth_check_session() -> Result<(), ServerFnError> {
    use actix_identity::Identity;
    use leptos_actix::*;

    let info: Option<Identity> = extract().await.unwrap_or_default();
    dbg!(info.is_some());
    Err(ServerFnError::ServerError("User is not connected".into()))
}
```
And an error i get is : 
```sh
error[E0432]: unresolved import `leptos_actix`
 --> src/db/user/auth.rs:6:9
  |
6 |     use leptos_actix::*;
  |         ^^^^^^^^^^^^ use of undeclared crate or module `leptos_actix`
  |

```

Using thaw 0.4.0-rc with features : `csr, hydrate, ssr` and defined it as : 
csr = [..., "thaw/csr"]
ssr = [..., "thaw/ssr"]
hydrate = [..., "thaw/hydrate"]

P.S Also getting error if try to apply `SSRMountStyleProvider` in `main.rs` aswell

**Comment by luoxiaozero** [comment]
Can I see your `Cargo.toml` file?

**Comment by ushinnary** [comment]
Sure : 
```toml
[package]
name = "secret"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
actix-files = { version = "0.6", optional = true }
actix-web = { version = "4", optional = true, features = ["macros"] }
actix-session = { version = "0.10.1", features = [
  "cookie-session",
], optional = true }
actix-identity = { version = "0.8.0", optional = true }
console_error_panic_hook = "0.1"
http = { version = "1.0.0", optional = true }
leptos = { version = "0.7", features = ["nightly"] }
leptos_meta = { version = "0.7" }
leptos_actix = { version = "0.7", optional = true }
leptos_router = { version = "0.7", features = ["nightly"] }
reactive_stores = "0.1"
wasm-bindgen = "=0.2.99"
thaw = { version = "0.4.0-rc", default-features = false, features = [
  "nightly",
  "ssr",
  "hydrate",
  "csr",
] }
surrealdb = { version = "2", optional = true }
icondata_core = "0.1.0"
icondata_ai = "0.0.10"
leptos_i18n = { version = "0.5.0-rc1" }
serde = { version = "*", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.6"
cfg-if = "1"

[features]
csr = ["leptos/csr", "thaw/csr"]
hydrate = ["leptos/hydrate", "thaw/hydrate", "leptos_i18n/hydrate"]
ssr = [
  "dep:actix-files",
  "dep:actix-web",
  "dep:leptos_actix",
  "dep:actix-session",
  "dep:actix-identity",
  "dep:surrealdb",
  "leptos/ssr",
  "leptos_meta/ssr",
  "leptos_router/ssr",
  "thaw/ssr",
  "leptos_i18n/actix",
]

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[package.metadata.leptos]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle. Defaults to the crate name
output-name = "secret"
# The site root folder is where cargo-leptos generate all output. WARNING: all content of this folder will be erased on a rebuild. Use it in your server setup.
site-root = "target/site"
# The site-root relative folder where all compiled output (JS, WASM and CSS) is written
# Defaults to pkg
site-pkg-dir = "pkg"
# [Optional] The source CSS file. If it ends with .sass or .scss then it will be compiled by dart-sass into CSS. The CSS is optimized by Lightning CSS before being written to <site-root>/<site-pkg>/app.css
style-file = "style/main.scss"
# Assets source dir. All files found here will be copied and synchronized to site-root.
# The assets-dir cannot have a sub directory with the same name/path as site-pkg-dir.
#
# Optional. Env: LEPTOS_ASSETS_DIR.
assets-dir = "assets"
# Tailwind integration
tailwind-input-file = "style/tailwind.css"
# The IP and port (ex: 127.0.0.1:3000) where the server serves the content. Use it in your server setup.
site-addr = "127.0.0.1:3005"
# The port to use for automatic reload monitoring
reload-port = 3001
# [Optional] Command to use when running end2end tests. It will run in the end2end dir.
#   [Windows] for non-WSL use "npx.cmd playwright test"
#   This binary name can be checked in Powershell with Get-Command npx
end2end-cmd = "npx playwright test"
end2end-dir = "end2end"
#  The browserlist query used for optimizing the CSS.
browserquery = "defaults"
# The environment Leptos will run in, usually either "DEV" or "PROD"
env = "DEV"
# The features to use when compiling the bin target
#
# Optional. Can be over-ridden with the command line parameter --bin-features
bin-features = ["ssr"]

# If the --no-default-features flag should be used when compiling the bin target
#
# Optional. Defaults to false.
bin-default-features = false

# The features to use when compiling the lib target
#
# Optional. Can be over-ridden with the command line parameter --lib-features
lib-features = ["hydrate"]

# If the --no-default-features flag should be used when compiling the lib target
#
# Optional. Defaults to false.
lib-default-features = false

# The profile to use for the lib target when compiling for release
#
# Optional. Defaults to "release".
lib-profile-release = "wasm-release"

[package.metadata.leptos-i18n]
default = "en"
locales = ["en", "fr"]
namespaces = ["layout"]

```
