### ISSUE TITLE
Flex custom style attributes lost after navigating in ssr mode

### ISSUE THREAD

**Issue by jerhat** [thaw-ui/thaw#344]
Custom `style` prop of `Flex` gets appended to the resulting Html correctly on first render. However after client side navigation in `ssr` mode, Flex's default style properties are lost.

E.g. given the below `Flex` definition:

`
<Flex
            vertical=true
            align=FlexAlign::End
            attr:style="color: red"
        >"Some red text"
        </Flex>
`

The following div is generated on the first render:

``` html
<div class="thaw-flex" style="display: flex;flex-direction: column;gap: 8px 12px;align-items: end;;color: red;">Some red text</div>
```

This is expected.

However when navigating away and then back to the same component, the following div is generated:

``` html
<div style="color: red" class="thaw-flex">Some red text</div>
```

Notice the `display`, `flex-firection`, ... properties are gone. I am expecting the same Html as for the first render.

Minimal reproducible example below. On initial load `Some red text` is right-aligned as expected. After navigating to `/pageblue` and back, the red text is left-aligned.

Is this a bug or are my expectations incorrect?

```rust
use components::{Route, Router, Routes};
use leptos::prelude::*;
use leptos_meta::{provide_meta_context, MetaTags};
use leptos_router::StaticSegment;
use leptos_router::*;
use thaw::*;

pub fn shell(options: LeptosOptions) -> impl IntoView {
    view! {
        <!DOCTYPE html>
        <html lang="en">
            <head>
                <meta charset="utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <AutoReload options=options.clone() />
                <HydrationScripts options/>
                <MetaTags/>
            </head>
            <body>
                <App/>
            </body>
        </html>
    }
}

#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();

    view! {

        <Router>
            <nav>
                <Link href="/">"Page Red"</Link>
                <Link href="/pageblue">"Page Blue"</Link>
                <br/ >
            </nav>
            <main>
                <Routes fallback=|| "Page not found.".into_view()>
                    <Route path=StaticSegment("/") view=PageRed />
                    <Route path=StaticSegment("/pageblue") view=PageBlue />
                </Routes>
            </main>
        </Router>
    }
}

#[component]
fn PageRed() -> impl IntoView {
    view! {
        <Flex vertical=true align=FlexAlign::End attr:style="color: red">
            "Some red text"
        </Flex>
    }
}

#[component]
fn PageBlue() -> impl IntoView {
    view! {
        <div style="display: flex;flex-direction: column;align-items: end;color: blue;">
            "Some blue text"
        </div>
    }
}
```

Relevant sections of `Cargo.toml`:

```toml
[dependencies]
leptos = { version = "0.7.0" }
leptos_router = { version = "0.7.0" }
axum = { version = "0.7", optional = true }
console_error_panic_hook = "0.1"
leptos_axum = { version = "0.7.0", optional = true }
leptos_meta = { version = "0.7.0" }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.5", features = ["fs"], optional = true }
wasm-bindgen = "=0.2.99"
thiserror = "1"
http = "1"
thaw = { version = "0.4.0-rc" }

[features]
hydrate = ["leptos/hydrate", "thaw/hydrate"]
ssr = [
    "dep:axum",
    "dep:tokio",
    "dep:tower",
    "dep:tower-http",
    "dep:leptos_axum",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "thaw/ssr",
]
```
